
services:
  flaskapimaria:
    build: .
    command: bash -c "python init_db.py && gunicorn -w 4 -b 0.0.0.0:5000 api_auto_payment:app"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    image: flaskapimaria
    environment:
      - FLASK_APP=api_auto_payment.py
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/app_db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
